export const statsData = [
  {
    id: "total",
    label: "موجودی کل",
    value: "1,245,850",
    unit: "دلار",
    change: "+4.16%",
    positive: true,
    color: "#2563EB",
    bgColor: "#EFF6FF",
    icon: "IconWallet",
  },
  {
    id: "transactions",
    label: "تراکنش‌های امروز",
    value: "287",
    unit: "تراکنش",
    change: "+18.3%",
    positive: true,
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    icon: "IconArrowsExchange",
  },
  {
    id: "profit",
    label: "سود خالص امروز",
    value: "12,650",
    unit: "دلار",
    change: "+5.6%",
    positive: true,
    color: "#059669",
    bgColor: "#ECFDF5",
    icon: "IconTrendingUp",
  },
  {
    id: "customers",
    label: "مشتریان فعال",
    value: "1,248",
    unit: "مشتری",
    change: "+12.7%",
    positive: true,
    color: "#D97706",
    bgColor: "#FFFBEB",
    icon: "IconUsers",
  },
];

export const chartData = [
  { day: "شنبه", amount: 850000, count: 210 },
  { day: "یکشنبه", amount: 1200000, count: 287 },
  { day: "دوشنبه", amount: 980000, count: 245 },
  { day: "سه‌شنبه", amount: 1450000, count: 320 },
  { day: "چهارشنبه", amount: 1100000, count: 275 },
  { day: "پنجشنبه", amount: 760000, count: 190 },
  { day: "جمعه", amount: 920000, count: 230 },
];

export const currencyData = [
  {
    name: "USD",
    label: "دلار آمریکا",
    value: 563850,
    percent: 45.2,
    color: "#2563EB",
    flag: "🇺🇸",
  },
  {
    name: "EUR",
    label: "یورو",
    value: 284350,
    percent: 28.8,
    color: "#7C3AED",
    flag: "🇪🇺",
  },
  {
    name: "IRR",
    label: "تومان ایران",
    value: 153600,
    percent: 12.3,
    color: "#DC2626",
    flag: "🇮🇷",
  },
  {
    name: "AFN",
    label: "افغانی",
    value: 119600,
    percent: 9.6,
    color: "#059669",
    flag: "🇦🇫",
  },
  {
    name: "TRY",
    label: "لیر ترکیه",
    value: 75950,
    percent: 6.1,
    color: "#D97706",
    flag: "🇹🇷",
  },
  {
    name: "Other",
    label: "سایر ارزها",
    value: 48500,
    percent: 3.5,
    color: "#94A3B8",
    flag: "🌍",
  },
];

export const transactionsData = [
  {
    id: 1,
    date: "۱۴۰۳/۰۴/۲۴ - ۱۱:۱۵",
    type: "انتقال حواله",
    typeColor: "#2563EB",
    typeBg: "#EFF6FF",
    desc: "دریافت از مشتری",
    from: "کابل",
    to: "دبی",
    currency: "USD",
    amount: 12450,
    customer: "احمد محمدی",
    status: "موفق",
  },
  {
    id: 2,
    date: "۱۴۰۳/۰۴/۲۴ - ۱۱:۱۰",
    type: "خرید ارز",
    typeColor: "#059669",
    typeBg: "#ECFDF5",
    desc: "خرید دلار",
    from: "افغانی",
    to: "دلار",
    currency: "USD",
    amount: 8750,
    customer: "سارا کریمی",
    status: "موفق",
  },
  {
    id: 3,
    date: "۱۴۰۳/۰۴/۲۴ - ۱۰:۵۵",
    type: "فروش ارز",
    typeColor: "#DC2626",
    typeBg: "#FEF2F2",
    desc: "فروش یورو",
    from: "یورو",
    to: "دلار",
    currency: "EUR",
    amount: 15600,
    customer: "علی رضایی",
    status: "موفق",
  },
  {
    id: 4,
    date: "۱۴۰۳/۰۴/۲۴ - ۱۰:۳۰",
    type: "دریافت نقدی",
    typeColor: "#7C3AED",
    typeBg: "#F5F3FF",
    desc: "واریز به حساب",
    from: "نقد",
    to: "حساب",
    currency: "AFN",
    amount: 25000,
    customer: "محمد اکبری",
    status: "موفق",
  },
  {
    id: 5,
    date: "۱۴۰۳/۰۴/۲۴ - ۱۰:۱۵",
    type: "انتقال حواله",
    typeColor: "#2563EB",
    typeBg: "#EFF6FF",
    desc: "پرداخت حواله به دبی",
    from: "کابل",
    to: "استانبول",
    currency: "TRY",
    amount: 7850,
    customer: "احمد محمدی",
    status: "موفق",
  },
  {
    id: 6,
    date: "۱۴۰۳/۰۴/۲۴ - ۰۹:۵۰",
    type: "تبدیل ارز",
    typeColor: "#D97706",
    typeBg: "#FFFBEB",
    desc: "تبدیل لیر به دلار",
    from: "TRY",
    to: "USD",
    currency: "USD",
    amount: 5250,
    customer: "رضا احمدی",
    status: "موفق",
  },
];

export const quickStats = {
  received: 45280,
  paid: 28740,
  profit: 12650,
  transactions: 287,
};

export const systemStatus = {
  status: "فعال",
  lastBackup: "امروز - ۰۳:۱۵",
  backupSize: "245.6 MB",
};

export const liveRates = [
  {
    name: "USD",
    label: "دلار آمریکا",
    rate: 71650,
    change: "+0.62%",
    positive: true,
    flag: "🇺🇸",
  },
  {
    name: "EUR",
    label: "یورو",
    rate: 76850,
    change: "+0.51%",
    positive: true,
    flag: "🇪🇺",
  },
  {
    name: "AFN",
    label: "افغانی",
    rate: 5.88,
    change: "+0.17%",
    positive: true,
    flag: "🇦🇫",
  },
  {
    name: "TRY",
    label: "لیر ترکیه",
    rate: 2150,
    change: "-0.21%",
    positive: false,
    flag: "🇹🇷",
  },
];
