export const orderReportStats = [
  { id: 'total',     label: 'کل گزارشات',         value: '8',   unit: 'گزارش', color: '#2563EB', bg: '#EFF6FF', icon: 'IconStar',    change: '+2',    positive: true },
  { id: 'active',    label: 'گزارشات فعال',        value: '6',   unit: 'گزارش', color: '#059669', bg: '#ECFDF5', icon: 'IconCircleCheck', change: '0', positive: true },
  { id: 'scheduled', label: 'زمانبندی شده',        value: '3',   unit: 'گزارش', color: '#7C3AED', bg: '#F5F3FF', icon: 'IconClock',   change: '+1',    positive: true },
  { id: 'issued',    label: 'صادر شده این ماه',    value: '18',  unit: 'مورد',  color: '#D97706', bg: '#FFFBEB', icon: 'IconDownload',change: '+5',    positive: true },
]

export const customReports = [
  {
    id: 1,
    name: 'گزارش عملکرد ماهانه شعب',
    desc: 'مقایسه عملکرد تمام شعب در یک ماه مشخص',
    fields: ['شعبه', 'عواید', 'مصارف', 'سود', 'تعداد تراکنش'],
    schedule: 'ماهانه',
    lastRun: '۱۴۰۳/۰۲/۰۱',
    nextRun: '۱۴۰۳/۰۳/۰۱',
    format: 'Excel',
    status: true,
    createdBy: 'احمد محمدی',
  },
  {
    id: 2,
    name: 'گزارش مشتریان VIP',
    desc: 'لیست مشتریان با موجودی بالای ۵۰,۰۰۰ دلار',
    fields: ['نام مشتری', 'موجودی', 'تعداد تراکنش', 'آخرین فعالیت'],
    schedule: 'هفتگی',
    lastRun: '۱۴۰۳/۰۲/۱۸',
    nextRun: '۱۴۰۳/۰۲/۲۵',
    format: 'PDF',
    status: true,
    createdBy: 'سارا کریمی',
  },
  {
    id: 3,
    name: 'گزارش حوالات خارجی',
    desc: 'تمام حوالات ارسالی و دریافتی خارج از کشور',
    fields: ['تاریخ', 'مبدا', 'مقصد', 'مبلغ', 'ارز', 'وضعیت'],
    schedule: 'روزانه',
    lastRun: '۱۴۰۳/۰۲/۲۴',
    nextRun: '۱۴۰۳/۰۲/۲۵',
    format: 'Excel',
    status: true,
    createdBy: 'احمد محمدی',
  },
  {
    id: 4,
    name: 'گزارش نرخ ارز هفتگی',
    desc: 'تغییرات نرخ ارزهای اصلی در طول هفته',
    fields: ['ارز', 'نرخ خرید', 'نرخ فروش', 'تغییر', 'بیشترین', 'کمترین'],
    schedule: 'هفتگی',
    lastRun: '۱۴۰۳/۰۲/۱۸',
    nextRun: '۱۴۰۳/۰۲/۲۵',
    format: 'PDF',
    status: true,
    createdBy: 'علی رضایی',
  },
  {
    id: 5,
    name: 'گزارش موجودی صندوق‌ها',
    desc: 'موجودی تمام صندوق‌ها به تفکیک ارز و شعبه',
    fields: ['شعبه', 'ارز', 'موجودی', 'تاریخ آخرین بروزرسانی'],
    schedule: 'روزانه',
    lastRun: '۱۴۰۳/۰۲/۲۴',
    nextRun: '۱۴۰۳/۰۲/۲۵',
    format: 'Excel',
    status: true,
    createdBy: 'مریم حسینی',
  },
  {
    id: 6,
    name: 'گزارش تراکنش‌های مشکوک',
    desc: 'تراکنش‌های با مبلغ بالا یا الگوی غیرمعمول',
    fields: ['تاریخ', 'مشتری', 'مبلغ', 'نوع', 'شعبه', 'دلیل بررسی'],
    schedule: 'روزانه',
    lastRun: '۱۴۰۳/۰۲/۲۴',
    nextRun: '۱۴۰۳/۰۲/۲۵',
    format: 'PDF',
    status: false,
    createdBy: 'احمد محمدی',
  },
]

export const reportHistory = [
  { id: 1,  reportName: 'گزارش عملکرد ماهانه شعب', runDate: '۱۴۰۳/۰۲/۲۴ - ۱۰:۳۰', format: 'Excel', size: '2.4 MB', runBy: 'سیستم (خودکار)', status: 'تکمیل' },
  { id: 2,  reportName: 'گزارش مشتریان VIP',        runDate: '۱۴۰۳/۰۲/۲۴ - ۰۹:۱۵', format: 'PDF',   size: '1.8 MB', runBy: 'احمد محمدی',     status: 'تکمیل' },
  { id: 3,  reportName: 'گزارش حوالات خارجی',        runDate: '۱۴۰۳/۰۲/۲۴ - ۰۸:۰۰', format: 'Excel', size: '3.2 MB', runBy: 'سیستم (خودکار)', status: 'تکمیل' },
  { id: 4,  reportName: 'گزارش نرخ ارز هفتگی',      runDate: '۱۴۰۳/۰۲/۲۳ - ۱۶:۰۰', format: 'PDF',   size: '0.9 MB', runBy: 'سارا کریمی',     status: 'تکمیل' },
  { id: 5,  reportName: 'گزارش موجودی صندوق‌ها',    runDate: '۱۴۰۳/۰۲/۲۳ - ۰۸:۰۰', format: 'Excel', size: '1.1 MB', runBy: 'سیستم (خودکار)', status: 'در پردازش' },
]
